ArmLib=new new Class({initialize:function(){},Globalization:function(a){$defined(a)&&(!0==a?(window.$Stage=this.$Stage,window.$Shapes=this.Shapes,window.$Rect=this.Shapes.$Rect,window.$Line=this.Shapes.$Line,window.$Image=this.Shapes.$Image,window.$Text=this.Shapes.$Text,window.$Circle=this.Shapes.$Circle,window.$Arc=this.Shapes.$Arc,window.$Curves=this.Shapes.$Curves,window.$Object=this.$Object):!1==a&&(delete window.$Stage,delete window.$Shapes,delete window.$Rect,delete window.$Line,delete window.$Image,
delete window.$Text,delete window.$Circle,delete window.$Arc,delete window.$Curves,delete window.$Object))},Stage:{},Shapes:{Rect:null,Line:null,Image:null,Text:null,Circle:null,Arc:null,Curves:null},Object:{}});var CSuperObj=new Class({initialize:function(){},context:null,x:0,y:0,globalCenter:{x:0,y:0},localCenter:{x:0,y:0},center:{x:0,y:0},angel:0,globalAngel:0,localAngel:0,rotateCenter:{x:0,y:0},localRotateCenter:{x:0,y:0},clone:function(){var a=[],c=function(b){if(null==b||"object"!=typeof b)return b;for(var f in a)if(a[f]==b)return b;a.push(b);if(isTFunc(b.constructor)&&"HTMLCollection"!=type(b)){f=new b.constructor;for(var g in b)if(b.hasOwnProperty(g))if("_context"==g)f[g]=b[g];else{var d=b.__lookupGetter__(g),
e=b.__lookupSetter__(g);d||e?(d&&f.prototype.__defineGetter__(g,d),e&&f.prototype.__defineSetter__(g,e)):f[g]=c(b[g])}}else return b;delete f.name;return f};return c(this)}});CShape=new Class({Extends:CSuperObj,x:0,y:0,stroke:"black",lineWidth:1,shapeType:"shape",type:"shape"});ArmLib.Shapes.$Rect=new Class({Extends:CShape,initialize:function(a){"undefined"!=typeof a&&(this.x=a.x||this.x,this.y=a.y||this.y,this.angel=a.angel||this.angel,this.stroke=a.stroke||this.stroke,this.fill=a.fill||this.fill,this.context=a.context||this.context,this.name=a.name||this.name,"undefined"!=typeof a.width&&0<a.width&&(this.width=a.width),"undefined"!=typeof a.height&&0<a.height&&(this.height=a.height),"undefined"!=typeof a.lineWidth&&0<a.lineWidth&&(this.lineWidth=a.lineWidth))},width:100,
height:100,fill:"gray",shapeType:"rect",_clean:function(){},_draw:function(){this.context.save();this.context.translate(this.x+this.width/2,this.y+this.height/2);this.context.rotate(this.angel*Math.PI/180);this.context.translate(-(this.x+this.width/2),-(this.y+this.height/2));this.context.beginPath();this.context.rect(this.x,this.y,this.width,this.height);this.context.closePath();this.context.fillStyle=this.fill;this.context.lineWidth=this.lineWidth;this.context.strokeStyle=this.stroke;this.context.fill();
this.context.stroke();this.context.restore()}});ArmLib.$Stage=new Class({initialize:function(a){if(a.container){var a=document.getElementById(a.container),c=document.createElement("canvas");c.width=this.width;c.height=this.height;c.style.id="2k2nd";a.appendChild(c);this.context=c.getContext("2d")}else throw Error("The container is not found! Choose right name of container, please!");this._init()},collection:[],collectionObjects:[],context:{},events:{},fps:10,intervalId:null,finfo:!1,width:500,height:500,TICKS_PER_SECOND:60,SKIP_TICKS:17,MAX_FRAMESKIP:5,
next_game_tick:1*new Date,add:function(a){if("object"==typeof a&&("shape"==a.type||"object"==a.type))a.context=this.context,this.collection.push(a),this.addObjCollection(a);else throw Error("Stage: add(O) -> O is not shape or object!");},remove:function(a){if("object"==typeof a&&("shape"==a.type||"object"==a.type))for(var c in this.collection)this.collection[c]==a&&delete this.collection[c];else throw Error("Stage: remove(O) -> O is not shape or object!");},addObjCollection:function(a){if(isTArmObject(a)){for(var c in a.collection)isTArmObject(a.collection)&&
this.addObjCollection(a.collection);this.collectionObjects.push(a)}},_init:function(){var a=this;document.onkeydown=function(c){a._onkeydown(c)}},_begin:function(a){for(var c in this.collection){var b=this.collection[c];"function"==typeof b._begin&&b._begin.call(b,a)}},_clean:function(a){this.context.clearRect(0,0,a.width,a.height)},_updateSkeleton:function(a){for(var c in this.collection){var b=this.collection[c];"function"==typeof b._updateSkeleton&&b._updateSkeleton.call(b,a)}},_update:function(a,
c){for(var b in this.collection){var f=this.collection[b];"function"==typeof f._update&&f._update.call(f,a,c)}},_draw:function(a){for(var c in this.collection){var b=this.collection[c];"function"==typeof b._draw&&b._draw.call(b,a)}},_info:function(){if(!0==this.finfo)for(var a in this.collection){var c=this.collection[a];"function"==typeof c._info&&c._info.call(c,this)}},_event:function(a){for(var c in this.collectionObjects){var b=this.collectionObjects[c];if(isSet(b.events)&&isTFunc(b.events.collision))for(var f in this.collectionObjects){var g=
this.collectionObjects[f];if(b!=g){var d=this.__collision(b,g);!0==d.flag&&b.events.collision.call(b,g,d.points,a)}}}},__collision:function(a,c){var b=[],f;for(f in a.functions)for(var g in c.functions){var d;d=a.functions[f];var e=c.functions[g];if(e.x0>=d.x0&&e.x0<=d.x1||e.x1>=d.x0&&e.x1<=d.x1||d.x0>=e.x0&&d.x0<=e.x1||d.x1>=e.x0&&d.x1<=e.x1){var i=d.A*e.B-d.B*e.A;if(1E-8>Math.abs(i))d={flag:!1};else{var h=-(d.C*e.B-d.B*e.C)/i;d=(d.x0<d.x1&&h>=d.x0&&h<=d.x1||d.x0>d.x1&&h>=d.x1&&h<=d.x0)&&(e.x0<e.x1&&
h>=e.x0&&h<=e.x1||e.x0>e.x1&&h>=e.x1&&h<=e.x0)?{x:h,y:-(d.A*e.C-d.C*e.A)/i,flag:!0}:{flag:!1}}}else d={flag:!1};d.flag&&b.push({x:d.x,y:d.y})}return 0<b.length?{flag:!0,points:b}:{flag:!1}},_onkeydown:function(a){for(var c in this.collection){var b=this.collection[c];isTFunc(b._onkeydown)&&b._onkeydown.call(b,a,this)}},_process:function(){this._clean.call(this,this);for(var a=(1*new Date+this.SKIP_TICKS-this.next_game_tick)/this.SKIP_TICKS,c=0;1*new Date>this.next_game_tick&&c<this.MAX_FRAMESKIP;)this._update.call(this,
this,a),this.next_game_tick+=this.SKIP_TICKS,c++;this._draw.call(this,this);for(a=0;a<c;a++)this._info.call(this,this),this._event.call(this,this)},run:function(){this._begin.call(this,this);var a=this;if(this.intervalId=setInterval(function(){a._process.call(a)},1E3/this.fps))console.log("Stage, run()");else throw Error("Stage, can't run!");},stop:function(){try{clearInterval(this.intervalId),console.log("Stage, stop()")}catch(a){console.log(a)}},info:function(){this.finfo=!1==this.finfo?!0:!1;console.log("Stage, info()");
return null}});ArmLib.Globalization(!0);
